### ISSUE TITLE
Why did you stop.. you are doing great job..

### ISSUE THREAD

**Issue by wisal-sarez** [mathall/rim#12]
I see less commit activity...  I wish I had contributed but I am still learning rust and new to system programming.

**Comment by mathall** [comment]
Thank you, it's nice to hear the work has been appreciated.
I'm currently in the midst of changing jobs and moving between continents. Side projects to me has always been about fun and learning, and rim has served that purpose. I may very well work on it again, but right now there's other things I need to prioritise.
However, always feel free to fork and hack away. :) After all, I didn't know any rust when I started writing the buffer module.
Thank you again and good luck, but I'm closing this issue!
