### ISSUE TITLE
Have you seen Kakoune? | Consider option to swap verb->object syntax /w object->verb

### ISSUE THREAD

**Issue by zenware** [mathall/rim#13]
It's got this nice object->verb pattern instead of verb->object and it highlights the object as you're typing the object selection keywords, so you can see if the verb you're about to apply will have the effect you intended. And it eliminates a lot of cases where one might need to undo and try again.

A friend sent me a link to this yesterday evening and I thought it was pretty interesting: http://kakoune.org/why-kakoune/why-kakoune.html

Would be cool to have the option to work in either way... I'm currently investigating adding kak-like functionality to neovim with a plugin, and hopefully that's fruitful.

**Comment by mathall** [comment]
Yes, Kakoune is a very interesting project.
Thanks for your enthusiasm, though I'm closing this as it's about changing features nowhere near implemented in rim.
