### ISSUE TITLE
Command line parsing (open file)

### ISSUE THREAD

**Issue by diogovk** [mathall/rim#8]
I'd like to be able to open files from the command line.

I've found two libraries for command line parsing.
Please check which one you like better.
http://rustbyexample.com/std_misc/arg/getopts.html
https://github.com/tailhook/rust-argparse

At first I'd implement only --version and --help, other than the filename to edit.
Please tell me your thoughts.

**Comment by mathall** [comment]
I haven't tried any of these and I've only giving them a glimpse now, so I can't say for sure which I like. [docopt](https://github.com/docopt/docopt.rs) is the most popular one I could find, and it seems easy to use. Do you have an opinion on this one?

**Comment by mathall** [comment]
merged!
